### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by draber** [jbout/rpg-monster-cards#4]
### Joel

- [x] ~~Add ID (auto increment) to library data~~ (no longer required)
- [x] ~~Map abbreviations to labels~~ (done)
- [x] ~~Review font list, separated by badge and card contents~~ (done)
- [x] ~~Define properties that can be edited~~ (configurable)
- [x] ~~Define properties that can be deactivated~~ (configurable)
- [x] ~~Define properties that are never displayed~~ (configurable)
- [x] ~~Define properties that are always displayed~~ (configurable)
- [ ] Come up with a better name in case you don't like _Ghastly ~~Beasts~~ Creatures_
- [x] ~~Come up with better names for the sections in case you don't like the existing ones~~ (done)
- [ ] Find a free _Slam card on the stage_ sound

### Dieter
- [x] Separate data types
- [x] Review font list, separated by badge and card contents
- [x] Review pattern list, separated by badge and card contents
- [x] Fix color component
- [x] Fix font component
- [x] Implement updated library
- [x] Investigate usage of tabs
- [x] ~~Enhance fraction calculator~~ (redundant)
- [x] ~~Investigate usage of Vue templates~~ (abandoned in favor of native Web Components)
- [x] ~~Implement template for card views~~ (abandoned in favor of native Web Components)
- [x] ~~Implement template for card forms~~ (abandoned in favor of native Web Components)
- [ ] Find a free _Slam card on the stage_ sound
